### ISSUE TITLE
Clearing Trades from existing professions is temporary

### ISSUE THREAD

**Issue by DaedalusGame** [Elecs-Mods/CustomVillagers#1]
This is probably less a bug than a petty annoyance

When clearing trades of an existing villager profession, for example 4 (vanilla butcher) and adding custom trades, it works as intended at first, but when trading with the villager enough times to unlock a new trade, it pulls a random hardcoded trade likely from the base implementation of the villager.

Is there a way to fix that or am I going to have to duplicate all the base villagers into custom professions?

**Comment by Elec332** [comment]
Hmmm, Ill look into this

**Comment by Elec332** [comment]
I have no solution for this (yet) for now, I suggest making your own to replace the villagers, because I dont see this issue being actually solved soon.
