### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jadedcat** [Elecs-Mods/CustomVillagers#2]
I really want to use this in my modpacks, but the wiki documentation seems incorrect. Is there a place we can find current documentation on configuring it?

**Comment by Elec332** [comment]
I am planning to update it todate (within 12 hours)

**Comment by jadedcat** [comment]
Okey dokey. I think this will add the final fine tuning to Magic Farm 3.

**Comment by Elec332** [comment]
Ok, there is quite some info on the wiki now (this repo's wiki), but it isnt done yet,
Ill leave this issue open 'till its completely done.

**Comment by jadedcat** [comment]
Still a bit confused, the configs show Input1, Input1 ammount, Input2, Input2ammount, return, returnammount . Is "return" what the villager gives the player? And input is what the player trades? And is it possible to set one of the inputs to "null"?

**Comment by Elec332** [comment]
@jadedcat 
MineTweaker integration is completed, its much easier to use that the default configs.
Documentation is being written as I write this
