### ISSUE TITLE
Reloading Minetweaker CustomVillagers Error

### ISSUE THREAD

**Issue by jadedcat** [Elecs-Mods/CustomVillagers#4]
Sometimes minetweaker needs to be reloaded after a world is launched. Using the /mt reload command while CustomVillager trades are in the scripts causes an error and an issue connecting to servers.

ModTweaker dev Jared says its possible to have CustomVillagers add something that makes their sections ignore /mt reload so the villager trades would only ever load on first launch.

**Comment by Elec332** [comment]
Fixed, new version will be uploaded to CF today.
